### ISSUE TITLE
Please clarify what types of agreements are AllowAdHocSubscriptions = false by default

### ISSUE THREAD

**Issue by UKayo** [MicrosoftDocs/powerbi-docs.ja-jp#10]
A tenant with EAS agreement was set to False, but a tenant with MPSA agreement was set to true. Please clarify.

 "If you acquired Power BI through a partner, this might be set to false, which means it is disabled." 

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: f9cf4ce3-f6b1-2c73-d0f9-44573242fb85
* Version Independent ID: fc6a52fd-db96-6e9f-f89a-3dea59bff3b7
* Content: [組織での Power BI のライセンス - Power BI](https://docs.microsoft.com/ja-jp/power-bi/service-admin-licensing-organization)
* Content Source: [powerbi-docs/service-admin-licensing-organization.md](https://github.com/MicrosoftDocs/powerbi-docs.ja-jp/blob/live/powerbi-docs/service-admin-licensing-organization.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/powerbi-docs #1190](https://github.com/MicrosoftDocs/powerbi-docs/issues/1190) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @Ukayo

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/powerbi-docs/issues/1190

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
