### ISSUE TITLE
About Private IP environment

### ISSUE THREAD

**Issue by YoshitakaTakada** [MicrosoftDocs/powerbi-docs.ja-jp#25]
Add the following as a cautionary note.
"When using Azure SQL Database with Private IP," On-premises data gateway is required. "

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 563a1b09-bcdc-2638-d9a0-6801b44d3cb0
* Version Independent ID: dea2c705-c2f7-3f2d-798b-ee41857e0ca2
* Content: [Power BI Desktop の DirectQuery - Power BI](https://docs.microsoft.com/ja-jp/power-bi/desktop-use-directquery)
* Content Source: [powerbi-docs/desktop-use-directquery.md](https://github.com/MicrosoftDocs/powerbi-docs.ja-jp/blob/live/powerbi-docs/desktop-use-directquery.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srvbpigh** [comment]
Hello, @YoshitakaTakada
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/powerbi-docs #1952](https://github.com/MicrosoftDocs/powerbi-docs/issues/1952) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @YoshitakaTakada, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/powerbi-docs/issues/1952. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
